### ISSUE TITLE
Cumulocity Runtime Widget Loader URL in the Doc leads to 404 page

### ISSUE THREAD

**Issue by nickponomar** [SoftwareAG/cumulocity-runtime-widget#2]
Dear Team,
please update Cumulocity Runtime Widget Loader link in the readme.
Thank you in advance!
Best,
Nick

**Comment by DarpanLalani** [comment]
Runtime widget loader is deprecated. Please use micro-frontend plugin with cumulocity 1016 onwards..
Please visit [Here](https://tech.forums.softwareag.com/t/microfrontends-for-cumulocity-iot-extending-solutions-with-the-power-of-ui-plugins/278257) for more details.
